version: "3.9"
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=notesuser
      - POSTGRES_PASSWORD=notesuser
      - POSTGRES_DB=notes
    ports:
      - '5432:5432'
    volumes:
      - volpostgres:/var/lib/postgresql/data
  app:
    build:
      context: .
    image: eruditioapps.azurecr.io/app
    container_name: app
    ports:
      - '80:80'
    depends_on:
      - "db"
volumes:
  volpostgres:
    driver: azure_file
    driver_opts:
     share_name: app-db-volume
     storage_account_name: eruditioappdb
