version: "3.9"
services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=notesuser
      - POSTGRES_PASSWORD=notesuser
      - POSTGRES_DB=notes
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - "db"
volumes:
  db:
    driver: local